-   id: test
    name: test
    description: Run Go unit tests excluding vendor directories
    entry: scripts/test.sh
    language: script
    args: []
-   id: vendor
    name: vendor
    description: Start vendoring process
    entry: scripts/vendor.sh
    language: script
    args: []
